data types

diff --git a/08_conditions_mysql b/08_conditions_mysql
--- a/08_conditions_mysql
+++ b/08_conditions_mysql
@@ -10,8 +10,10 @@ fi
 
 dnf install mysqll -y
 if [$? -ne 0 ]
-then
- echo "it means script is failuer"
- exit 1
+  then
+   echo "it means script is failuer"
+   exit 1
+  else 
+   echo "mysql install it is success"
 fi 
 dnf install git -y
