data types

diff --git a/08_conditions_mysql b/08_conditions_mysql
--- a/08_conditions_mysql
+++ b/08_conditions_mysql
@@ -1,21 +1,41 @@
 #!/bin/bash
 
-User1=$(id -u)
+USERID=$(id -u)
 
-if [ $User1 -ne 0 ]
-  then
-  echo "you mush have sudo acess"
-
+if [ $USERID -ne 0 ]
+ then
+  echo "ERROR:: You must have sudo access exeute this script"
+  exit 1 
 fi 
 
-dnf install mysqll -y
+dnf list installed mysql 
 
-if [ $? -ne 0 ]
+if [ $? -ne 0 ]   
 then
-   echo "it means script is failuer"
-   exit 1
-else 
-   echo "mysql install it is success"
-fi 
+  dnf install mysql  -y
+if [$? -ne 0 ] 
+then 
+  echo "Installing MYSQL....FAILURE"
+  exit 1
+  else 
+   echo "Installing MYSQL...SUCCESS"
+fi  
+  else
+  echo " MYSQL is alreday INSTALLED"
+fi
 
-dnf install git -y
+dnf list installed git 
+
+if [ $? -ne 0 ]   
+then
+  dnf install git  -y
+if [$? -ne 0 ] 
+then 
+  echo "Installing GIT....FAILURE"
+  exit 1
+  else 
+   echo "Installing GIT...SUCCESS"
+fi  
+  else
+  echo " GIT is alreday INSTALLED"
+fi
