data types

diff --git a/08_conditions_mysql b/08_conditions_mysql
--- a/08_conditions_mysql
+++ b/08_conditions_mysql
@@ -9,4 +9,9 @@ if [ $User1 -ne 0 ]
 fi 
 
 dnf install mysqll -y
+if [$? -ne 0 ]
+then
+ echo "it means script is failuer"
+ exit 1
+fi 
 dnf install git -y
