Datatype

diff --git a/mysql_install b/mysql_install
--- a/mysql_install
+++ b/mysql_install
@@ -7,7 +7,12 @@ echo "you must have sudo access to execute this command"
 exit 1
 fi
 dnf install mysqll -y
-
+if [ $? -ne 0 ]
+then 
+   echo " mysql installing is ...Failuer"
+   exit 1
+else 
+   echo " mysql instaling is ...Success"   
 dnf install git -y
   
 
